// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Day_17.Models;

public partial class Person
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Age { get; set; }

    public string City { get; set; }

    public string Country { get; set; }
}